name: Publish Npm Package

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v10.20.10

jobs:
  Npm-Publish:
    # prevents this action from running on forks
    if: github.repository == 'snapre/github-actions-practiceeeeeeeeeeeeee'
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Set node version to 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        run: pnpm install

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        run: pnpm run ci-publish -- ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}